spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: postgres
    password: Tirth_22

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: my-secret-key
