spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: ${DB_PASSWORD:Tirth_22}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:my-secret-key}

management:
  endpoints:
    web:
      exposure:
        include: health,info
