spring:
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:${RENDER_EXTERNAL_HOSTNAME:eureka-server}}

management:
  tracing:
    enabled: false
