spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
  kafka:
    bootstrap-servers: kafka:9092
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

# Distributed Tracing
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

# Swagger/OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
