spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
  kafka:
    bootstrap-servers: kafka:9092
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
