server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neighborhood_request_db
    username: postgres
    password: Tirth_22

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      provider-service:
        slidingWindowSize: 10
        failureRateThreshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    service-name: request-service

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
