-- Update provider_db constraints
ALTER TABLE providers DROP CONSTRAINT IF EXISTS providers_service_type_check;
ALTER TABLE providers ADD CONSTRAINT providers_service_type_check CHECK (service_type::text IN ('PLUMBER', 'ELECTRICIAN', 'TEACHING', 'CLEANING', 'DELIVERY', 'PAINTING', 'HOME_MAINTENANCE', 'GARDENING', 'PET_CARE', 'BABYSITTING', 'CARPENTRY', 'MOVING', 'COOKING', 'LAUNDRY', 'GROCERY_SHOPPING', 'ELDERLY_CARE', 'HVAC_REPAIR', 'APPLIANCE_REPAIR', 'IT_SUPPORT', 'PHOTOGRAPHY', 'TAILORING', 'CAR_WASHING', 'PEST_CONTROL', 'FITNESS_TRAINING', 'BEAUTY_SALON', 'OTHER'));
